fix: use outer join to get other users
BetterSocial/admin-system pull request #172
Opened 2023-09-18 14:10 UTC by brm-stnd

di querynya saya tidak menambahkan default 0 pada field follower_count karena by default postgree sudah menambahkan 0 ketika countnya null

2023-09-18 15:52 UTC, brm-stnd commented
> Old migration should not be edited anymore, since it will change the integrity of the DB

fixed

2023-09-18 16:19 UTC, fajarism requested changes
Migration is swapped each other

2023-09-18 16:19 UTC, fajarism commented on database/migrations/2023_09_18_154312_create_vwm_user_follower_count_v2.php
> +            FULL OUTER JOIN users B
Use right outer join
If use full outer join, there will be null value on the left

Also please filter on user that is not anonymous

2023-09-18 16:32 UTC, fajarism requested changes

2023-09-19 15:50 UTC, fajarism requested changes

2023-09-19 15:50 UTC, fajarism commented on database/migrations/2023_09_18_175818_create_vwm_user_topic_follower_count_v2.php
> +        WITH DATA
Old migration
Use 2023_09_14_142046_create_vwm_user_topic_follower_count_rank_v5
`
CREATE MATERIALIZED VIEW vwm_user_topic_follower_count_rank
        AS
        SELECT
            *
        FROM (
            SELECT
                A.topic_id,
                C.follower_count as follower_count,
                ROW_NUMBER() OVER(
                    PARTITION BY A.topic_id
                    ORDER BY C.follower_count DESC
                ) AS topic_follower_rank,
                B.*
            FROM
                vwm_user_follower_count C
            INNER JOIN
                users B
            ON C.user_id_followed = B.user_id
            INNER JOIN
                user_topics A
            ON
                C.user_id_followed = A.user_id
						WHERE B.profile_pic_path NOT LIKE '%default-profile-picture%'
            GROUP BY
                A.topic_id,
                B.user_id,
                C.follower_count
            ) AS user_topic_by_follower_count
        WHERE
            user_topic_by_follower_count.topic_follower_rank <= 11
        ORDER BY
            user_topic_by_follower_count.topic_id ASC,
            user_topic_by_follower_count.topic_follower_rank ASC
        WITH DATA"
`

2023-09-20 14:56 UTC, fajarism requested changes
2023_09_18_175818_create_vwm_user_topic_follower_count_v2.php is still using old migration

2023-09-20 15:23 UTC, fajarism approved these changes

2023-09-20 15:23 UTC, fajarism commented
Good job mas @brm-stnd

2023-09-20 15:23 UTC, merged